name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches: [ main ]  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # or match your local Ruby version
          bundler-cache: true

      - name: Install Ruby dependencies
        run: bundle install

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or match your local Node.js version
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build JavaScript assets
        run: npm run data && npm run build

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Ensure this only runs on the main branch, even if the push is to a different branch and build is triggered
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
